apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: address-space-controller
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enmasse.io:address-space-controller
subjects:
- kind: ServiceAccount
  name: address-space-controller
  namespace: enmasse-infra
