apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "enmasse.io:enmasse-operator-enmasse-infra"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enmasse.io:enmasse-operator
subjects:
- kind: ServiceAccount
  name: enmasse-operator
  namespace: enmasse-infra
