kind: Deployment
apiVersion: apps/v1
metadata:
  name: enmasse-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: enmasse
    name: enmasse-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: enmasse-operator
  template:
    metadata:
      labels:
        app: enmasse
        name: enmasse-operator
      annotations:
        enmasse.io/version: "0.33.0"
        enmasse.io/revision: "df633ee2aa5faaad3612b5babe9b5fb3e62a93c4"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-role.enmasse.io/operator-infra
                    operator: In
                    values:
                      - "true"
      serviceAccountName: enmasse-operator
      containers:
      - name: controller
        image: quay.io/enmasse/controller-manager:0.33.0
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REVISION
          value: "df633ee2aa5faaad3612b5babe9b5fb3e62a93c4"
        - name: VERSION
          value: "0.33.0"
        - name: CONTROLLER_ENABLE_MESSAGING_INFRASTRUCTURE
          value: "false"
        - name: OPERATOR_NAME
          value: "enmasse-operator"
        - name: IMAGE_PULL_POLICY
          value: "IfNotPresent"
        - name: CONTROLLER_DISABLE_ALL
          value: "true"
        - name: CONTROLLER_ENABLE_UPGRADER
          value: "true"
        - name: CONTROLLER_ENABLE_AUTHENTICATION_SERVICE
          value: "true"
        - name: CONTROLLER_ENABLE_ADDRESS_SPACE_CONTROLLER
          value: "true"
        - name: CONTROLLER_ENABLE_MESSAGING_USER
          value: "true"
        - name: RELATED_IMAGE_ADDRESS_SPACE_CONTROLLER
          value: quay.io/enmasse/address-space-controller:0.33.0
        - name: RELATED_IMAGE_CONTROLLER_MANAGER
          value: quay.io/enmasse/controller-manager:0.33.0
        - name: RELATED_IMAGE_ROUTER
          value: quay.io/interconnectedcloud/qdrouterd:1.12.0
        - name: RELATED_IMAGE_STANDARD_CONTROLLER
          value: quay.io/enmasse/standard-controller:0.33.0
        - name: RELATED_IMAGE_AGENT
          value: quay.io/enmasse/agent:0.33.0
        - name: RELATED_IMAGE_BROKER
          value: quay.io/enmasse/artemis-base:2.13.0-ARTEMIS-2810
        - name: RELATED_IMAGE_BROKER_PLUGIN
          value: quay.io/enmasse/broker-plugin:0.33.0
        - name: RELATED_IMAGE_TOPIC_FORWARDER
          value: quay.io/enmasse/topic-forwarder:0.33.0
        - name: RELATED_IMAGE_NONE_AUTHSERVICE
          value: quay.io/enmasse/none-authservice:0.33.0
        - name: RELATED_IMAGE_KEYCLOAK
          value: quay.io/enmasse/keycloak-openshift:4.8.3.Final
        - name: RELATED_IMAGE_KEYCLOAK_PLUGIN
          value: quay.io/enmasse/keycloak-plugin:0.33.0
        - name: CONTROLLER_ENABLE_CONSOLE_SERVICE
          value: "true"
        - name: RELATED_IMAGE_CONSOLE_INIT
          value: "quay.io/enmasse/console-init:0.33.0"
        - name: RELATED_IMAGE_CONSOLE_SERVER
          value: "quay.io/enmasse/console-server:0.33.0"
        - name: RELATED_IMAGE_CONSOLE_PROXY_OPENSHIFT
          value: "quay.io/openshift/origin-oauth-proxy:latest"
        - name: RELATED_IMAGE_CONSOLE_PROXY_OPENSHIFT3
          value: "openshift/oauth-proxy:latest"
        - name: RELATED_IMAGE_CONSOLE_PROXY_KUBERNETES
          value: "quay.io/oauth2-proxy/oauth2-proxy:v5.1.0"
        - name: CONSOLE_LINK_SECTION_NAME
          value: "Messaging"
        - name: CONSOLE_LINK_NAME
          value: "EnMasse Console"
        - name: CONSOLE_LINK_IMAGE_URL
          value: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iNzlweCIgaGVpZ2h0PSI3OXB4IiB2aWV3Qm94PSIwIDAgNzkgNzkiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8IS0tIEdlbmVyYXRvcjogU2tldGNoIDQyICgzNjc4MSkgLSBodHRwOi8vd3d3LmJvaGVtaWFuY29kaW5nLmNvbS9za2V0Y2ggLS0+CiAgICA8dGl0bGU+dmVyc2lvbnM8L3RpdGxlPgogICAgPGRlc2M+Q3JlYXRlZCB3aXRoIFNrZXRjaC48L2Rlc2M+CiAgICA8ZGVmcz48L2RlZnM+CiAgICA8ZyBpZD0iUGFnZS0xIiBzdHJva2U9Im5vbmUiIHN0cm9rZS13aWR0aD0iMSIgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj4KICAgICAgICA8ZyBpZD0idmVyc2lvbnMiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0zMDguMDAwMDAwLCAtNzIuMDAwMDAwKSI+CiAgICAgICAgICAgIDxlbGxpcHNlIGlkPSJDb21iaW5lZC1TaGFwZS1Db3B5LTIiIGZpbGw9IiMwMDQ5OUUiIGN4PSIzNDcuNSIgY3k9IjExMS41IiByeD0iMjQuNSIgcnk9IjI0LjUiPjwvZWxsaXBzZT4KICAgICAgICAgICAgPHBhdGggZD0iTTMzOSwxMDIuNjkxMDE0IEMzMzksMTAyLjY5MTAxNCAzNDIuNjkwMjE1LDk0LjQxMDUzMjMgMzUwLjIwNTY1MSwxMDAuOTM1OTEyIEwzNTEuMDE1Njk5LDEwMS43NDU5NTkgQzM1MS4wMTU2OTksMTAxLjc0NTk1OSAzNTIuNzI1Nzk4LDEwMy41MDEwNjEgMzUzLjQ0NTg0LDEwMy41MDEwNjEgQzM1NC4xNjU4ODIsMTAzLjUwMTA2MSAzNTQuMjU1ODg3LDEwMy40MTEwNTYgMzU1Ljk2NTk4NiwxMDEuNzAwOTU2IEMzNTcuNjc2MDg2LDk5Ljk5MDg1NjggMzU3LjQwNjA3LDEwMC4wMzU4NTkgMzU5Ljg4MTIxNCw5Ny43ODU3Mjg2IEMzNjIuMzU2MzU4LDk1LjUzNTU5NzcgMzY1LjY3MTUyMSw5My45MzA1MzQ0IDM2NS42NzE1MjEsOTMuOTMwNTM0NCBDMzY1LjY3MTUyMSw5My45MzA1MzQ0IDM2Ny4yOTE2MTUsOTIuOTEwNDE1MSAzNzAuMjYxNzg4LDkyLjE2MDQwMTUgQzM3My4yMzE5Niw5MS40MTAzODc5IDM3Ny40MDk3MzMsOTAuNjUyODEzOSAzODIsOTEuMTcwMzQ0IEMzODIsOTEuMTcwMzQ0IDM4MC4xMzIzOTEsOTIuMjUwNDA2NyAzNzcuOTI3MjYzLDk4Ljk1NTc5NjYgQzM3NS43MjIxMzUsMTA1LjY2MTE4NiAzNzQuNTA3MDY0LDEwNy43MzEzMDcgMzc0LjUwNzA2NCwxMDcuNzMxMzA3IEMzNzQuNTA3MDY0LDEwNy43MzEzMDcgMzcxLjg1MTkxLDExMy4zNTY2MzQgMzY1LjQ2MTUzOCwxMTQuNTcxNzA0IEMzNjUuNDYxNTM4LDExNC41NzE3MDQgMzY4LjY1NjcyNCwxMTguMzk2OTI3IDM3OS45OTczODQsMTE3LjEzNjg1NCBDMzc5Ljk5NzM4NCwxMTcuMTM2ODU0IDM1OC4wODExMDksMTMxLjE3NzY3IDM0OC4yNzA1MzksMTE0Ljg0MTcyIEMzNDguMDQ4OTQ2LDExNC4zNDQyNjEgMzQ1Ljg0OTM5OCwxMTAuMDI1NDUgMzQ1LjMwMDM2NiwxMDguMjExMzA1IEMzNDQuNjEwMjk2LDEwNS45MzEyMDIgMzQ0LjMwOTEzOSwxMDUuMTI1Mzg1IDM0My4yOTAyNzksMTA0LjE2MTA2OSBDMzQwLjc3MDEzMywxMDEuNzc1OTMxIDMzOSwxMDIuNjkxMDE0IDMzOSwxMDIuNjkxMDE0IiBpZD0iRmlsbC0xLUNvcHktNyIgZmlsbD0iIzc1QTBEMyI+PC9wYXRoPgogICAgICAgIDwvZz4KICAgIDwvZz4KPC9zdmc+"
        - name: ENABLE_MONITORING
          value: "true"
