apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: brokered-topic
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: enmasse
spec:
  displayName: Brokered Topic
  displayOrder: 0
  shortDescription: Creates a topic on a broker.
  longDescription: Creates a topic on a broker.
  addressType: topic
  resources:
    broker: 0.0
