apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: brokered-deadletter
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: enmasse
spec:
  displayName: Brokered Dead Letter
  displayOrder: 0
  shortDescription: Creates a dead letter queue on a broker.
  longDescription: Creates a dead letter queue on a broker.
  addressType: deadletter
