apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-medium-multicast
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: enmasse
spec:
  displayName: Medium Multicast
  displayOrder: 1
  shortDescription: Creates a medium multicast address.
  longDescription: Creates a medium multicast address where messages go via a router that does not take ownership of the messages.
  addressType: multicast
  resources:
    router: 0.01
