apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-large-anycast
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: enmasse
spec:
  displayName: Large Anycast
  displayOrder: 2
  shortDescription: Creates a large anycast address.
  longDescription: Creates a large anycast address where messages go via a router that does not take ownership of the messages.
  addressType: anycast
  resources:
    router: 0.1
