apiVersion: admin.enmasse.io/v1beta1
kind: BrokeredInfraConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: enmasse
spec:
  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 512Mi
      storage: 5Gi
    addressFullPolicy: FAIL
    globalMaxSize: 64Mb
