apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-large-topic
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: enmasse
spec:
  displayName: Large Topic
  displayOrder: 2
  shortDescription: Creates a large topic backed by a dedicated broker.
  longDescription: Creates a large topic backed by a dedicated broker.
  addressType: topic
  resources:
    router: 0.1
    broker: 1.0
