apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-deadletter
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: enmasse
spec:
  displayName: Dead Letter
  displayOrder: 0
  shortDescription: Creates a dead letter queue.
  longDescription: Creates a dead letter queue.
  addressType: deadletter
